### ISSUE TITLE
testnet

### ISSUE THREAD

**Issue by benzmuircroft** [sebicas/bitcoin-sniffer#4]
how do we listen to testnet

I've tried searching google for a list of testnet ips / nodes but I got nothing whatsoever!

Also tried same ip(s) as main net but with the port set to 8332

**Comment by sebicas** [comment]
Sorry, is not prepared to listen to testnet.

**Comment by benzmuircroft** [comment]
What must i change to make it prepared?

**Comment by sebicas** [comment]
This needs to be changed ( See https://en.bitcoin.it/wiki/Testnet )
- Testnet network protocol listen port is 18333 (instead of 8333)
- Default RPC connection port is 18332 (instead of 8332)
- A different value of ADDRESSVERSION field ensures no testnet Bitcoin addresses will work on the production network. (0x6F rather than 0x00)
- The protocol message header bytes are 0x0B110907 (instead of 0xF9BEB4D9)

For example in here:
https://github.com/sebicas/bitcoin-sniffer/blob/master/sniffer.py#L73

But search for "\x00" since is in a lot of other places.

If you make it work on testnet, you are welcome to send me pull request.

**Comment by benzmuircroft** [comment]
cool
